stuff:
	# avrdude -c arduino -patmega328p -P /dev/ttyUSB0 -b115200 -u -V -U flash:w:fiesta.hex
	avrdude -c arduino -patmega328p -P /dev/ttyACM0 -b115200 -u -V -U flash:w:fiesta.hex
	# avrdude -c arduino -patmega328p -P /dev/ttyACM0 -b115200 -u -V -U flash:w:fiesta.hex
